### ISSUE TITLE
build-k8s-ranger.sh is missing

### ISSUE THREAD

**Issue by exolab** [mr3project/mr3-run-k8s#1]
Hi,

I am looking at the guide for running ranger. 

https://mr3docs.datamonad.com/docs/k8s/guide/run-ranger/

Right off the bat, I run into this problem:

```
Building a Docker image for Ranger

To build a Docker image for Ranger, collect all necessary files in the directory kubernetes/ranger by executing the script build-k8s-ranger.sh.
```

As far as I can tell that script does not exist. As build-ranger.sh later references the image built in the first step, I am a bit lost

Can you help? Really looking forward to getting this to work :+1: 

Kind regards
Toby

**Comment by mr3project** [comment]
Hi,

I see that the first paragraph of the documentation is quite confusing. You need to download an MR3 release which includes build-k8s-range.sh in the root directory. For example, you can download hivemr3-1.2-hive3.1.2-k8s.tar.gz
from:

https://github.com/mr3project/mr3-release/releases/tag/v1.2

Then, you can change the directory to kubernetes/ where you can find run-ranger.sh for executing Ranger:

gla@plvi:~/temp/hivemr3-1.2-hive3.1.2-k8s$ ls build-k8s-ranger.sh 
build-k8s-ranger.sh
gla@plvi:~/temp/hivemr3-1.2-hive3.1.2-k8s$ ls kubernetes/run-ranger.sh 
kubernetes/run-ranger.sh

If you have already built a Ranger docker image, you need only mr3-run-k8s.git which contains run-ranger.sh. (This is what's meant in the first paragraph of the documentation.)

Best,

--- Sungwoo
